appium/node-teen_process

README.md
lib/teen_process.js
test/subproc-specs.js

This PR adds a new method to `SubProcess` called `join()`. It can be used to wait for the process to finish - it's, IMHO, the missing piece between `start()` and `stop()`.

Introduce SubProcess.join()

---

package.json
test/exec-specs.js
test/fixtures/bad_exit.bat
test/fixtures/echo with space.bat
test/fixtures/echo.bat
test/fixtures/env.bat
test/fixtures/sleepyproc.bat
test/fixtures/traphup.bat
test/helpers.js
test/subproc-specs.js

This PR addresses most of the windows issues.
Windows still has a hard time `.spawn`ing if both the cmd path and an argument contain spaces.
There are no quick-fixes that suit us at this stage without rewriting how we handle processes. Looks like it has recently been addressed: https://github.com/nodejs/node/pull/4598
Resolves #6
CC @imurchie

Fixed Windows tests

---

lib/teen_process.js

Get better handling of errors in the stdio streams within `exec`. I'm hoping this provides better support for EPIPE errors that sometimes crop up.

Add error handling on standard streams

---

lib/teen_process.js

Otherwise after the process has started, if the start detector does any sort of logging we can get log lines that are confusing.

Get rid of start detector after start has been detected

---

.travis.yml
lib/teen_process.js

In calling code we keep having to do things like `if (sp.proc) sp.stop();` The calling code should not depend on internal details of the implementation of `SubProcess`. So add a method to check if it is running.

Add isRunning getter to SubProcess

---

lib/teen_process.js
test/fixtures/bad_exit.sh

As a first step to figuring out where the deprecation warning are coming from when processes cannot be stopped, add the cmd that is the basis of the process to the error message.
@jlipps

Add cmd to stop failure notice

---

lib/teen_process.js

```2017-07-27 04:20:56:578 - error: [simctl] TypeError: Cannot read property 'on' of undefined
at ../../lib/teen_process.js:39:15
at F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
at exec (../../lib/teen_process.js:25:10)
at callee$1$0$ (../../lib/simctl.js:38:18)
at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/r …
```

Avoid an unexpected crash if any of streams is ignored and thus undefined

---

package.json

This `source-map-support` version seems old. This version can cause process blocking issue because uncaught exceptions which can appears when fetching `*.map` files are not handled (such as `.map` file does not exist).
I update it to the new version since https://github.com/appium/appium is using `0.4.14`.
Thanks.

Update source-map-support version

---

README.md
lib/teen_process.js

This option will allow to run `.bat` and `.sh` files, which is sometimes needed by script, like [apksigner](https://github.com/appium/appium-adb/pull/277#issuecomment-351951434)

Add 'shell' option to be able to run shell scripts

---

lib/subprocess.js

The current logging is generally good, but there are cases where multiple processes may be running with the same basic command. Log all the arguments so that the exact process is distinguishable.

Add args to error message when command cannot be stopped

---

lib/exec.js
lib/subprocess.js
package.json
test/subproc-specs.js

If the error message does not have the command in it, it is difficult to trace back to what process erred. And with it, the command can easily be manually run when there is a problem.

Add command to timeout error message

---

lib/subprocess.js
test/subproc-specs.js

There are places where we use `unref` (see, for instance, https://github.com/appium/appium-xcuitest-driver/blob/master/lib/utils.js#L200, https://github.com/appium/appium-xcuitest-driver/blob/master/lib/wda/iproxy.js#L58), and get the `pid` (see, for instance, https://github.com/appium/appium-xcuitest-driver/blob/master/lib/wda/utils.js#L244) on the internal `proc`. This is a bad practice.

Add method to unref underlying proc

---

package.json

It looks like `bluebird` and `lodash` are required in non-development files, which causes dependency issues using the new Yarn Plug n' Play features. 
Alternatively these could be moved to `peerDependencies` to allow application authors to control these packages.

Move non-dev dependencies to dependencies as required by lib/subprocess.js

---

README.md
lib/exec.js

For long-running processes we may still want to use `exec` (if we don't need the process control in `SubProcess`) but logging the output as it happens may be advantageous.

Add option to inline log during exec

---

lib/subprocess.js

The current logic is fine if we are getting a textual output with short strings separated by line breaks. Although, there will be serious memory issues if the output is binary. the PR limits the maximum size of stored strings by 64KB.

Make sure the last line logic would never cause a memory leak

---

lib/exec.js
lib/helpers.js
package.json

This PR should not modify any actual code, but rather add some docstrings to describe the public API of `exec()`.
Eventually we could derive a `.d.ts` from this, or move some stuff into `.d.ts`, but this will do for now.
Note: There is a potential bug where we check if `error.errno === 'ENOENT'`, since that property is now `code`.  It may have been `errno` once upon a time.  `errno` is now a `number`.  this likely is true in all maintained versions of Node.js.  I did not attempt to address this.

chore: add some types

---

.eslintrc
.github/workflows/node.js.yml
gulpfile.js
index.js
lib/index.js
lib/subprocess.js
package.json
test/exec-specs.js
test/fixtures/bad_exit.sh
test/helpers.js
test/subproc-specs.js

BREAKING CHANGE
This PR updates the dev dependencies to use `@appium/support`, `@appium/gulp-plugins` and `@appium/eslint-config-appium`, away from the unmaintained (non-scoped) packages.
Due to the requirements of these deps, it's unlikely that a dev environment older than Node.js v14 / npm v6 will work.  Thus, Node.js v8, v10, and v12 are officially dropped (though they may still work; this change should not affect the published, "production" library).
An organizational change was needed for the `@appium/gulp-plugins` upgrade; `index.js` moved to `lib/index.js`, and `index.js` is now a CJS file which re-exports `build/lib/index.js`.
In addition:
- modified some tests to ensure that child processes were being cleanly shut down
- modified the `bad_exit.sh` fixture for BSD `sleep` compat

chore(deps): upgrade deps

---

package-lock.json
package.json

this will fix the peer dependency issues renovate is having.
I think to prevent this in the future, we'd need to group the eslint deps with `@appium/eslint-config-appium` in the renovate config. that can be another PR.

chore(): update eslint et. al

---

lib/exec.js
lib/helpers.js
lib/subprocess.js
package-lock.json
package.json
test/exec-specs.js
test/helpers.js
test/subproc-specs.js

According to https://nodejs.org/api/child_process.html#child_processspawncommand-args-options ENOENT is also thrown if cwd option is invalid.
Also removed the unnecessary dependency to appium/support

fix: Add ENOENT validation for cwd options

---

.github/workflows/node.js.yml

since this caused:
```
Run npm i -g npm
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: npm@10.1.0
npm ERR! notsup Not compatible with your version of node/npm: npm@10.1.0
npm ERR! notsup Required: {"node":"^18.17.0 || >=20.[5](https://github.com/appium/node-teen_process/actions/runs/6129595144/job/16637854438?pr=311#step:4:6).0"}
npm ERR! notsup Actual:   {"npm":"8.19.4","node":"v1[6](https://github.com/appium/node-teen_process/actions/runs/6129595144/job/16637854438?pr=311#step:4:7).20.2"}
```
https://github.com/appium/node-teen_process/actions/runs/6129595144/job/16637854438?pr=311
So far, latest nodejs v16 installs npm v9+ so we do not need this npm update part

ci: remove npm update

---

index.js
package.json
tsconfig.json

It looks like typescript generates ESM module by default. This requires major version bump though, so reverting

fix: Restore CJS

---

lib/subprocess.js
test/subproc-specs.js

It provides a buffer output so that encoding can be handled directly at the usage site.

feat: [subprocess] support output as buffer
